!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 16
  - - clip_range
    - 0.3
  - - ent_coef
    - 0.00017182124670595984
  - - gae_lambda
    - 0.98
  - - gamma
    - 0.99
  - - learning_rate
    - 8.170508912845396e-05
  - - max_grad_norm
    - 2
  - - n_envs
    - 1
  - - n_epochs
    - 20
  - - n_steps
    - 256
  - - n_timesteps
    - 10000.0
  - - normalize
    - true
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(activation_fn=nn.Tanh)
  - - vf_coef
    - 0.826807936319546
